import { PlantModelDto } from '../map-loader/opentcs-xml.parser';
import { detectSingleVehicleBlocks } from './corridor-detector';

/** Prefix marking a block as auto-generated by the corridor detector. */
export const GENERATED_BLOCK_PREFIX = 'SVB-';

/**
 * Populate a plant model's `blocks` with freshly-detected single-file-corridor
 * `SINGLE_VEHICLE_ONLY` blocks so the kernel scheduler serialises lane access
 * and multi-AGV deadlock on one-lane / dead-end passages is prevented at the
 * allocation layer.
 *
 * Idempotent and non-destructive: previously generated `SVB-*` blocks are
 * dropped and recomputed, while any hand-authored (non-`SVB-*`) blocks are kept.
 * Mutates and returns the same model for convenient chaining.
 */
export function applySingleVehicleBlocks(model: PlantModelDto): PlantModelDto {
  const manual = model.blocks.filter(
    (b) => !b.name.startsWith(GENERATED_BLOCK_PREFIX),
  );
  const generated = detectSingleVehicleBlocks(model.paths);
  model.blocks = [...manual, ...generated];
  return model;
}
