import { PlantModelDto } from '../map-loader/opentcs-xml.parser';
import { detectSingleVehicleBlocks } from './corridor-detector';

/** Prefix marking a block as auto-generated by the corridor detector. */
export const GENERATED_BLOCK_PREFIX = 'SVB-';

/**
 * Populate a plant model's `blocks` with freshly-detected single-file-corridor
 * `SINGLE_VEHICLE_ONLY` blocks so the kernel scheduler serialises lane access
 * and multi-AGV deadlock on one-lane / dead-end passages is prevented at the
 * allocation layer.
 *
 * Idempotent and non-destructive: previously generated `SVB-*` blocks are
 * dropped and recomputed, while any hand-authored (non-`SVB-*`) blocks are kept.
 * A lane already covered by a hand-authored block is NOT regenerated, so the
 * same column never ends up double-blocked (manual block + `SVB-*`).
 * Mutates and returns the same model for convenient chaining.
 */
export function applySingleVehicleBlocks(model: PlantModelDto): PlantModelDto {
  const manual = model.blocks.filter(
    (b) => !b.name.startsWith(GENERATED_BLOCK_PREFIX),
  );
  // Every point/path already inside a hand-authored block. The detector skips a
  // lane whose dead-end tip is in here, so manual and generated blocks never
  // overlap on the same lane.
  const reserved = new Set(manual.flatMap((b) => b.memberNames));
  const generated = detectSingleVehicleBlocks(model.paths, reserved);
  model.blocks = [...manual, ...generated];
  return model;
}
