servicewebapi.enable=true
servicewebapi.bindAddress=0.0.0.0
servicewebapi.bindPort=59200
rmikernelinterface.enable=true
rmikernelinterface.useSsl=false
rmikernelinterface.registryPort=1499
rmikernelinterface.remoteKernelServicePortalPort=59000
rmikernelinterface.remotePlantModelServicePort=59000
rmikernelinterface.remoteTransportOrderServicePort=59000
rmikernelinterface.remoteVehicleServicePort=59000
rmikernelinterface.remoteNotificationServicePort=59000
rmikernelinterface.remoteSchedulerServicePort=59000
rmikernelinterface.remoteRouterServicePort=59000
rmikernelinterface.remoteDispatcherServicePort=59000
rmikernelinterface.remoteQueryServicePort=59000
rmikernelinterface.remotePeripheralServicePort=59000
rmikernelinterface.remotePeripheralJobServicePort=59000
commadapter.vehicle.vda5050.mqtt.brokerHost=mqtt-broker
commadapter.vehicle.vda5050.mqtt.brokerPort=1883
commadapter.vehicle.vda5050.mqtt.connectionEncrypted=false
commadapter.vehicle.vda5050.mqtt.clientId=wes-dev-opentcs-vda5050
commadapter.vehicle.vda5050.mqtt.keepAliveInterval=10000
commadapter.vehicle.vda5050.mqtt.reconnectInterval=5000
kernelapp.vehicleResourceManagementType=LENGTH_IGNORED
